### ISSUE TITLE
Wall Jump / Wall Slide tuning parameters

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#78]
__EDIT: Re-purposing this issue to be the one to add tuning parameters. Base functionality will be handled on its own__

We may not need these for the sake of the jam, but they would be cool to have because... well who doesn't like wall jumping?

This should first include a wall friction parameter. Probably makes sense to have something along the lines of:

* 0 means no wall friction, functionality the same as if this didn't exist
* -1 means infinite wall friction, so the player will just latch onto the wall
* any positive number will have some sort of calculation go into it to dictate how fast a player will move down the wall

__Perhaps it makes more sense to have the parameter be `wallSlideSpeed` and the higher the number the faster you slide down the wall.__ Meaning
* 0 means you stick to the wall
* -1 means you don't attache to the wall at all
* Positive numbers mean you slide down, higher numbers meaning you slide faster

**Comment by Kenoshen** [comment]
Really what you are measuring is how much you stick to a wall, not how fast you fall down it.  You are basically saying you want to scale gravity by some factor 0-1 when touching a wall.  If you are talking about speed down the wall, you could have a situation where jumping into a wall SHOOTS you down, which doesn't sound like the intended purpose of wall jumping.  The "stickiness" of a wall should be from 0-1.

0 = you completely stick to the wall because gravity while you touch the wall is multiplied by 0
1 = you have NO stickiness and you slide down the wall as if the feature doesn't exist because gravity is multiplied by 1

At least, thats my thought on that.

Another thing you could do is in the game code, we could have it so that when the player jumps against a wall we set the stickiness to 0.  And then, as time passes x^2 that up to 1.  And only let them wall jump if their wall stickiness is above like... 0.5?  So that way they have to do the wall jump soon after hitting the wall or else they just slide down it again.  I'm not sure how realistic that would be in code, I'm just thinking of scenarios to use this in.

**Comment by MondayHopscotch** [comment]
My original write up was based on games like the megaman x series and super metabolism (though I didn't play that much so my recollection might be inaccurate). 

At least in megaman, you basically have a fixed speed you slide down walls at, and it's noticeably slower than your free fall speed.

That said, I'm actually a fan of the feel you've described. I think if we could do both, that'd be amazing. Yours would probably be easier to implement, so it probably makes sense to do that way first and re-evaluate after that's in.

**Comment by MondayHopscotch** [comment]
One piece I need to add to this issue: also introduce new player states (JumperState enum) to handle these new things. I think we'll just need something like 

* `right_wall_slide`
* `left_wall_slide`

**Comment by MondayHopscotch** [comment]
With #107 This should be much more easy now.
